### PR TITLE
Filemover Fix

### PR DESCRIPTION
**Pull request by CalaxDev**
Fix: Now also works on Desktop
Fix: Now correctly combines a Path and a Path or a File reliably; Path may or may not end with a \ now. (E.g. ^F11::Filemover("C:\folder" or "C:\folder"\")

### CODE REVIEW

**Comment by Z3roCoder** [comment]
A fix from your side is no longer needed - Fixed it myself and updated the PR

**Comment by TaranVH** [comment]
thank you sir!
The script is currently working after I added a \ to the right place.
I'll try this version as well, but it might be a little while before I merge it.
Code I don't understand always makes me nervous...
Oh hey, what would really help me is,
Can you write something that will CHECK to see if the folder location EXISTS?
My script doesn't do that right meow. So it just fails if the network is down and the location is not available. I get an annoying AHK error message.

**Comment by Z3roCoder** [comment]
Sure, I can do that.
Instead of writing here, can I reach you on any Email, Messenger or something? That'd make it a bit easier :p

**Comment by Z3roCoder** [comment]
Is there still something you might need assistance in? I've got a bunch of free time right now, so I could offer you my 'services' (if you wanna call it that) to help/code some stuff

**Comment by Z3roCoder** [comment]
My offer still stands :P

**Pull request closed without merging**
