### PR TITLE
Adeed Speed(), Reverse(), showVideoKeyFrames()

### PR DESCRIPTION
**Pull request by Matesaktesak**
**I added a few simple scripts at the end of the file.**

Also renamed preset() to prPreset as I made the function for AE as well.

I have changed the prFocus to work on Czech layout keyboards. Remove whole InstantVFX and SFX as I wasn't able to make them work...
I have deleted some comments and stuff that I didn't understand.
I added a few simple scripts at the end of the file.

### CODE REVIEW

**Comment by TaranVH** [comment]
No way I can merge this. Like I say in the readme, I cannot compromise my daily working scripts for anyone. I'll never merge any changes to my premiere functions or all keyboards scripts.
You did clean up a lot of junk comments. It should be done, but I must do it myself.
You did stuff like change **ctrl alt shift K** to just **k** by itself. Scripts should never send bare keypresses if they can avoid it. Always use the CTRL modifier at least. This way, you don't get a "k" typed somewhere you don't want it. It can only ever be shuttle stop. It's all about reducing cross-talk.
You also didn't comment as to what your shortcuts like ctrl F10 are doing... or indeed what your functions are supposed to be doing in general.
good work, and I'm glad it works for you. But my working scripts must only ever be changed by me.

**Comment by Z3roCoder** [comment]
@Matesaktesak 
I'd just wanna add one thing:

Why do you think just removing comments of someone elses work is a good idea? Just because you "didn't understand them"? Doesn't mean Taran doesn't understand them either.

**Comment by TaranVH** [comment]
It's totally fine for him to do that, IF he's using the scripts for himself.
Not OK if he's trying to merge it back.
Programming etiquette is just another thing that must be learned - I can't fault Matesaktesak for that.

**Comment by Matesaktesak** [comment]
I am extremely sorry for the mess I made, when I wrote this pull request I didn't think of consequences for others.

I have changed the shuttle stop, because I use it on daily basis.

I thought that you will merge just the 3 new scripts at the end. I didn't fully understand that it merges all changes...

Again I am very sorry for the time it took you to read the script and respond.

**Pull request closed without merging**
