### PR TITLE
 Use the interception.rar and check description (Not tested!!!!!)

### PR DESCRIPTION
**Pull request by danielalexis**
Hi Taran! I have compiled interception to use 99 keyboards so it should work for you now, still uses the same command line installer

### CODE REVIEW

**Comment by dxf** [comment]
Please can we get a video demo of more than 10 keyboards? haha

**Comment by TaranVH** [comment]
Indeed. many people have claimed to have solved this 10-device limit, but so far, none have.
If you don't have 11 keyboards to test with, you can always just unplug and re-plug multiple times. It uses a new driver each time.

**Comment by Matesaktesak** [comment]
Even if you promise it works - I will be still a bit skeptical - and I will first run it in a virtual box :-) I once nearly got a trojan virus from a binary compiled by my friend...

**Comment by danielalexis** [comment]
Im closing this since this is dead, but hey taran use Razer synapse, they have Hypershift which I think you'll like it @TaranVH

**Pull request closed without merging**
