### PR TITLE
[ImgBot] optimizes images

### PR DESCRIPTION
**Pull request by JamesKingdom**
*Total -- 11,495.40kb -> 9,176.18kb (20.18%)

/2nd keyboard support files/anti-flicker-filter_000.png -- 14.56kb -> 0.42kb (97.08%)
/FYI/KEYCAP IMAGES for STREAM DECK/horizontal anchor.png -- 47.01kb -> 1.50kb (96.81%)
/2nd keyboard support files/scale_D2017.png -- 14.71kb -> 0.53kb (96.43%)
/2nd keyboard support files/rotation_D2017.png -- 14.74kb -> 0.53kb (96.38%)
/2nd keyboard support files/anchor_point_vertical_D2017.png -- 15.27kb -> 0.61kb (96.01%)
/2nd keyboard support files/anchor_point_D2017.png -- 14.86kb -> 0.61kb (95.87%)
/2nd keyboard support files/a1_unlocked_targeted.png -- 14.82kb -> 0.63kb (95.73%)
/2nd keyboard support files/v1_ALT_unlocked_targeted.png -- 14.82kb -> 0.63kb (95.72%)
/2nd keyboard support files/v1_unlocked_targeted.png -- 14.80kb -> 0.63kb (95.71%)
/2nd keyboard support files/CROP transform button.png -- 14.97kb -> 0.65kb (95.66%)
/2nd keyboard support files/anti-flicker-filter.png -- 14.94kb -> 0.68kb (95.46%)
/FYI/KEYCAP IMAGES for STREAM DECK/Folder-white.png -- 15.98kb -> 0.85kb (94.7%)
/FYI/KEYCAP IMAGES for STREAM DECK/Folder-grey.png -- 16.02kb -> 0.87kb (94.57%)
/FYI/KEYCAP IMAGES for STREAM DECK/Folder-orange.png -- 16.96kb -> 0.92kb (94.57%)
/FYI/KEYCAP IMAGES for STREAM DECK/Folder-orange-red.png -- 16.10kb -> 0.92kb (94.31%)
/FYI/KEYCAP IMAGES for STREAM DECK/Folder-red.png -- 16.08kb -> 0.92kb (94.31%)
/FYI/KEYCAP IMAGES for STREAM DECK/Folder-green.png -- 16.16kb -> 1.01kb (93.72%)
/FYI/KEYCAP IMAGES for STREAM DECK/Folder-blue.png -- 16.24kb -> 1.03kb (93.67%)
/FYI/KEYCAP IMAGES for STREAM DECK/Folder-lime.png -- 16.24kb -> 1.04kb (93.58%)
/FYI/KEYCAP IMAGES for STREAM DECK/Folder-pink.png -- 16.28kb -> 1.06kb (93.47%)
/FYI/KEYCAP IMAGES for STREAM DECK/Folder-cyan.png -- 16.28kb -> 1.06kb (93.47%)
/FYI/KEYCAP IMAGES for STREAM DECK/Folder.png -- 15.39kb -> 1.06kb (93.09%)
/FYI/KEYCAP IMAGES for STREAM DECK/reselect.png -- 17.08kb -> 1.85kb (89.17%)
/FYI/KEYCAP IMAGES for STREAM DECK/BACK.png -- 17.44kb -> 2.21kb (87.34%)
/FYI/KEYCAP IMAGES for STREAM DECK/7db.png -- 17.47kb -> 2.40kb (86.27%)
/FYI/KEYCAP IMAGES for STREAM DECK/extra scripts.PNG -- 21.74kb -> 5.00kb (76.98%)
/FYI/KEYCAP IMAGES for STREAM DECK/Folder-grey-missing.png -- 23.47kb -> 5.47kb (76.7%)
/FYI/KEYCAP IMAGES for STREAM DECK/extra keyboard scripts white.png -- 21.99kb -> 5.22kb (76.24%)
/FYI/KEYCAP IMAGES for STREAM DECK/Folder-cyan-missing.png -- 23.73kb -> 5.73kb (75.86%)
/FYI/KEYCAP IMAGES for STREAM DECK/audio left.png -- 20.57kb -> 4.99kb (75.73%)
/FYI/KEYCAP IMAGES for STREAM DECK/color PURPLE.png -- 1.25kb -> 0.32kb (74.67%)
/FYI/KEYCAP IMAGES for STREAM DECK/color SKY BLUE.png -- 12.08kb -> 3.22kb (73.37%)
/FYI/KEYCAP IMAGES for STREAM DECK/vertical anchor.png -- 6.05kb -> 1.77kb (70.67%)
/FYI/KEYCAP IMAGES for STREAM DECK/audio blank.png -- 20.79kb -> 6.69kb (67.81%)
/FYI/KEYCAP IMAGES for STREAM DECK/premiere folder 1.png -- 29.68kb -> 9.99kb (66.35%)
/FYI/KEYCAP IMAGES for STREAM DECK/premiere folder 4.png -- 27.51kb -> 9.97kb (63.78%)
/FYI/KEYCAP IMAGES for STREAM DECK/crop none.png -- 22.69kb -> 8.33kb (63.29%)
/FYI/KEYCAP IMAGES for STREAM DECK/premiere folder 2.png -- 27.86kb -> 10.24kb (63.23%)
/FYI/KEYCAP IMAGES for STREAM DECK/premiere folder 3.png -- 28.47kb -> 10.85kb (61.89%)
/FYI/KEYCAP IMAGES for STREAM DECK/enter white.jpg -- 13.41kb -> 5.43kb (59.52%)
/FYI/KEYCAP IMAGES for STREAM DECK/v1 a1 lock - green.png -- 25.15kb -> 10.34kb (58.88%)
/FYI/KEYCAP IMAGES for STREAM DECK/enter black.jpg -- 13.20kb -> 5.43kb (58.82%)
/FYI/KEYCAP IMAGES for STREAM DECK/v1 a1 lock.png -- 24.46kb -> 10.10kb (58.7%)
/FYI/KEYCAP IMAGES for STREAM DECK/windowSpy.PNG -- 24.93kb -> 10.32kb (58.6%)
/FYI/KEYCAP IMAGES for STREAM DECK/fx search.png -- 23.82kb -> 9.90kb (58.44%)
/FYI/KEYCAP IMAGES for STREAM DECK/full folder.jpg -- 24.22kb -> 10.41kb (57.02%)
/FYI/KEYCAP IMAGES for STREAM DECK/remove effects.png -- 26.97kb -> 11.81kb (56.23%)
/FYI/KEYCAP IMAGES for STREAM DECK/%fit.png -- 1.94kb -> 0.86kb (55.91%)
/FYI/KEYCAP IMAGES for STREAM DECK/blur.png -- 92.41kb -> 40.78kb (55.87%)
/FYI/KEYCAP IMAGES for STREAM DECK/pin to clip.png -- 25.41kb -> 11.49kb (54.78%)
/FYI/KEYCAP IMAGES for STREAM DECK/full folder reversed.jpg -- 27.29kb -> 12.75kb (53.28%)
/FYI/KEYCAP IMAGES for STREAM DECK/Explorer-name expand.png -- 7.36kb -> 3.54kb (51.95%)
/FYI/KEYCAP IMAGES for STREAM DECK/color BLACK.png -- 0.60kb -> 0.29kb (51.87%)
/FYI/KEYCAP IMAGES for STREAM DECK/circle.png -- 3.75kb -> 1.86kb (50.49%)
/FYI/KEYCAP IMAGES for STREAM DECK/crop left.png -- 6.94kb -> 3.49kb (49.71%)
/FYI/KEYCAP IMAGES for STREAM DECK/color Orange-ish.png -- 0.58kb -> 0.31kb (47.57%)
/FYI/KEYCAP IMAGES for STREAM DECK/color GREEN.png -- 0.85kb -> 0.45kb (47.4%)
/FYI/KEYCAP IMAGES for STREAM DECK/color WHITE.png -- 0.55kb -> 0.30kb (45.95%)
/FYI/KEYCAP IMAGES for STREAM DECK/paste 4.png -- 5.47kb -> 3.05kb (44.21%)
/FYI/KEYCAP IMAGES for STREAM DECK/paste 1.png -- 5.69kb -> 3.18kb (44.14%)
/FYI/KEYCAP IMAGES for STREAM DECK/zoom monitor in.png -- 8.39kb -> 4.74kb (43.55%)
/FYI/KEYCAP IMAGES for STREAM DECK/zoom monitor fit.png -- 8.47kb -> 4.81kb (43.19%)
/FYI/KEYCAP IMAGES for STREAM DECK/explorer.png -- 31.11kb -> 17.79kb (42.81%)
/FYI/KEYCAP IMAGES for STREAM DECK/paste 6.png -- 7.45kb -> 4.29kb (42.44%)
/FYI/KEYCAP IMAGES for STREAM DECK/paste 2.png -- 6.93kb -> 4.01kb (42.23%)
/FYI/KEYCAP IMAGES for STREAM DECK/paste 3.png -- 7.25kb -> 4.21kb (41.99%)
/FYI/KEYCAP IMAGES for STREAM DECK/zoom monitor out.png -- 9.45kb -> 5.50kb (41.75%)
/FYI/KEYCAP IMAGES for STREAM DECK/paste 8.png -- 7.80kb -> 4.56kb (41.59%)
/FYI/KEYCAP IMAGES for STREAM DECK/paste 5.png -- 6.46kb -> 3.79kb (41.39%)
/FYI/KEYCAP IMAGES for STREAM DECK/paste 7.png -- 6.36kb -> 3.74kb (41.26%)
/FYI/KEYCAP IMAGES for STREAM DECK/Explorer-arrange date.png -- 7.89kb -> 4.65kb (41.09%)
/FYI/KEYCAP IMAGES for STREAM DECK/color bars.png -- 10.95kb -> 6.48kb (40.83%)
/FYI/KEYCAP IMAGES for STREAM DECK/photoshop logo.png -- 20.67kb -> 12.24kb (40.78%)
/FYI/KEYCAP IMAGES for STREAM DECK/Explorer-arrange name.png -- 8.08kb -> 4.84kb (40.08%)
/FYI/KEYCAP IMAGES for STREAM DECK/zoom-fit.png -- 1.54kb -> 0.94kb (39.33%)
/FYI/KEYCAP IMAGES for STREAM DECK/template2.png -- 77.03kb -> 46.99kb (39.01%)
/FYI/KEYCAP IMAGES for STREAM DECK/crop top.png -- 5.49kb -> 3.36kb (38.87%)
/FYI/KEYCAP IMAGES for STREAM DECK/crop bottom.png -- 5.38kb -> 3.33kb (38.11%)
/FYI/KEYCAP IMAGES for STREAM DECK/multiply.png -- 62.93kb -> 41.34kb (34.3%)
/FYI/KEYCAP IMAGES for STREAM DECK/flip vertical.png -- 2.60kb -> 1.74kb (33.15%)
/FYI/KEYCAP IMAGES for STREAM DECK/notepad++.png -- 49.67kb -> 34.24kb (31.07%)
/FYI/KEYCAP IMAGES for STREAM DECK/premiere.png -- 14.72kb -> 10.22kb (30.58%)
/FYI/KEYCAP IMAGES for STREAM DECK/firefox.png -- 47.75kb -> 33.16kb (30.55%)
/FYI/KEYCAP IMAGES for STREAM DECK/impact flash 1.png -- 60.46kb -> 43.22kb (28.51%)
/FYI/KEYCAP IMAGES for STREAM DECK/audio blank BLACK.png -- 20.07kb -> 14.52kb (27.65%)
/2nd keyboard support files/timelineUniqueLocator2.png -- 0.96kb -> 0.70kb (26.9%)
/2nd keyboard support files/timelineUniqueLocator.png -- 0.96kb -> 0.70kb (26.75%)
/FYI/KEYCAP IMAGES for STREAM DECK/chrome.png -- 46.02kb -> 33.96kb (26.2%)
/FYI/KEYCAP IMAGES for STREAM DECK/impact flash 2.png -- 59.05kb -> 43.69kb (26%)
/FYI/KEYCAP IMAGES for STREAM DECK/word.png -- 21.35kb -> 15.84kb (25.81%)
/FYI/KEYCAP IMAGES for STREAM DECK/thumb_14670028780Explorer.png -- 20.68kb -> 15.72kb (24%)
/FYI/tarans startup folder JULY 2017 - these are the scripts I actually use.png -- 50.05kb -> 38.26kb (23.57%)
/FYI/tarans startup folder DEC 2017.png -- 53.86kb -> 42.02kb (21.98%)
/FYI/tarans startup folder Nov 2016 - before functions and assignments were seperated.PNG -- 33.74kb -> 26.53kb (21.37%)
/FYI/KEYCAP IMAGES for STREAM DECK/push up.png -- 26.70kb -> 21.22kb (20.54%)
/FYI/KEYCAP IMAGES for STREAM DECK/pan up.png -- 7.97kb -> 6.37kb (20.07%)
/FYI/KEYCAP IMAGES for STREAM DECK/push down.png -- 27.29kb -> 21.87kb (19.87%)
/FYI/How i use the Stream Deck to launch AHK scripts directly rather than using a keyboard shortcut.png -- 533.86kb -> 435.82kb (18.37%)
/FYI/KEYCAP IMAGES for STREAM DECK/impact flash 3.png -- 43.33kb -> 35.40kb (18.3%)
/FYI/KEYCAP IMAGES for STREAM DECK/1--- VIEW OF ALL IMAGE NAMES for easy navigation on Github.png -- 421.81kb -> 344.73kb (18.27%)
/FYI/KEYCAP IMAGES for STREAM DECK/word BLACK.png -- 12.39kb -> 10.15kb (18.11%)
/FYI/KEYCAP IMAGES for STREAM DECK/pan down.png -- 7.46kb -> 6.13kb (17.81%)
/FYI/KEYCAP IMAGES for STREAM DECK/push left.png -- 28.38kb -> 23.36kb (17.7%)
/FYI/KEYCAP IMAGES for STREAM DECK/pan right.png -- 6.77kb -> 5.62kb (17.01%)
/FYI/How i use the Stream Deck to launch AHK scripts directly rather than using a keyboard shortcut - with annotations.png -- 687.11kb -> 572.84kb (16.63%)
/FYI/KEYCAP IMAGES for STREAM DECK/flip horizontal.png -- 3.04kb -> 2.55kb (16.2%)
/FYI/KEYCAP IMAGES for STREAM DECK/push right.png -- 27.31kb -> 22.93kb (16.05%)
/FYI/KEYCAP IMAGES for STREAM DECK/delivery.png -- 8.08kb -> 6.82kb (15.58%)
/FYI/KEYCAP IMAGES for STREAM DECK/1-1.png -- 3.25kb -> 2.75kb (15.41%)
/FYI/KEYCAP IMAGES for STREAM DECK/copy 4.png -- 6.32kb -> 5.35kb (15.31%)
/FYI/KEYCAP IMAGES for STREAM DECK/pan left.png -- 6.68kb -> 5.67kb (15.14%)
/FYI/KEYCAP IMAGES for STREAM DECK/rotation.png -- 14.43kb -> 12.35kb (14.46%)
/FYI/KEYCAP IMAGES for STREAM DECK/1-4.png -- 3.92kb -> 3.38kb (13.79%)
/FYI/Taran desk Dec 2017.png -- 2,780.67kb -> 2,400.82kb (13.66%)
/FYI/KEYCAP IMAGES for STREAM DECK/ltt color.PNG -- 29.35kb -> 25.60kb (12.78%)
/FYI/KEYCAP IMAGES for STREAM DECK/%100.png -- 13.20kb -> 11.56kb (12.48%)
/FYI/KEYCAP IMAGES for STREAM DECK/%400.png -- 13.30kb -> 11.66kb (12.32%)
/FYI/all_Tarans_keyboard_labels_5.png -- 4,020.33kb -> 3,525.52kb (12.31%)
/FYI/KEYCAP IMAGES for STREAM DECK/copy 3.png -- 7.45kb -> 6.54kb (12.12%)
/FYI/KEYCAP IMAGES for STREAM DECK/copy 1.png -- 6.30kb -> 5.54kb (12.04%)
/FYI/KEYCAP IMAGES for STREAM DECK/%200.png -- 14.09kb -> 12.40kb (11.98%)
/FYI/KEYCAP IMAGES for STREAM DECK/1-2.png -- 4.91kb -> 4.33kb (11.82%)
/FYI/KEYCAP IMAGES for STREAM DECK/%50.png -- 12.56kb -> 11.08kb (11.79%)
/FYI/KEYCAP IMAGES for STREAM DECK/%25.png -- 12.34kb -> 10.90kb (11.7%)
/FYI/KEYCAP IMAGES for STREAM DECK/ltt pending.png -- 4.76kb -> 4.21kb (11.63%)
/FYI/KEYCAP IMAGES for STREAM DECK/%10.png -- 11.93kb -> 10.54kb (11.63%)
/FYI/KEYCAP IMAGES for STREAM DECK/copy 2.png -- 7.23kb -> 6.40kb (11.56%)
/FYI/KEYCAP IMAGES for STREAM DECK/crop right.png -- 6.50kb -> 5.76kb (11.39%)
/FYI/KEYCAP IMAGES for STREAM DECK/%75.png -- 12.07kb -> 10.72kb (11.18%)
/FYI/KEYCAP IMAGES for STREAM DECK/ltt archive.png -- 4.81kb -> 4.29kb (10.85%)
/FYI/KEYCAP IMAGES for STREAM DECK/1-16.png -- 5.45kb -> 4.90kb (10.19%)
/FYI/KEYCAP IMAGES for STREAM DECK/zoom-out.png -- 6.76kb -> 6.07kb (10.16%)
/FYI/KEYCAP IMAGES for STREAM DECK/audio right.png -- 6.89kb -> 6.20kb (10.02%)
/FYI/KEYCAP IMAGES for STREAM DECK/fap pending.png -- 6.14kb -> 5.53kb (9.99%)
/FYI/KEYCAP IMAGES for STREAM DECK/1-8.png -- 5.21kb -> 4.69kb (9.89%)
/FYI/KEYCAP IMAGES for STREAM DECK/crop 50%.png -- 11.60kb -> 10.47kb (9.73%)
/FYI/KEYCAP IMAGES for STREAM DECK/fap archive.png -- 6.20kb -> 5.62kb (9.37%)
/2nd keyboard support files/v1_ALT_locked_targeted.png -- 0.95kb -> 0.86kb (8.99%)
/FYI/KEYCAP IMAGES for STREAM DECK/zoom-in.png -- 5.49kb -> 5.01kb (8.63%)
/2nd keyboard support files/transform_icon_D2017.png -- 0.68kb -> 0.62kb (8.62%)
/FYI/KEYCAP IMAGES for STREAM DECK/csf pending.png -- 6.46kb -> 5.96kb (7.71%)
/FYI/KEYCAP IMAGES for STREAM DECK/master_clip.png -- 15.31kb -> 14.14kb (7.65%)
/FYI/KEYCAP IMAGES for STREAM DECK/csf archive.png -- 6.60kb -> 6.13kb (7.15%)
/FYI/Taran desk Mar 2017.jpg -- 572.64kb -> 535.59kb (6.47%)
/FYI/KEYCAP IMAGES for STREAM DECK/zoom 2.png -- 15.11kb -> 14.14kb (6.44%)
/FYI/KEYCAP IMAGES for STREAM DECK/warp.png -- 6.61kb -> 6.19kb (6.34%)
/2nd keyboard support files/v1_locked_targeted.png -- 0.90kb -> 0.85kb (5.01%)
/FYI/KEYCAP IMAGES for STREAM DECK/dissolve 1.png -- 48.75kb -> 46.46kb (4.7%)
/FYI/KEYCAP IMAGES for STREAM DECK/zoom 1.png -- 9.27kb -> 9.05kb (2.38%)
/2nd keyboard support files/v1_locked_untargeted.png -- 0.87kb -> 0.85kb (2.25%)
/FYI/KEYCAP IMAGES for STREAM DECK/dissolve 2.png -- 61.77kb -> 61.00kb (1.24%)
/FYI/KEYCAP IMAGES for STREAM DECK/thumb_Folder.png -- 8.13kb -> 8.05kb (0.96%)

### CODE REVIEW

**Comment by wormeyman** [comment]
@JamesKingdom Since some of these are used to auto place the mouse have you confirmed that this still works after optimization?

**Comment by TaranVH** [comment]
My thoughts exactly. These images are already really small. they're designed to be printed, or used for extremely precise image searching and cursor placement. I deliberately didn't save them as jpegs.
Is this lossless compression? If not, I can't use these.

**Comment by wormeyman** [comment]
@JamesKingdom Example:  https://github.com/TaranVH/2nd-keyboard/blob/master/All%20Premiere%20Functions.ahk#L742

I assume this is lossless compression where you just toss the metadata or something but please let us know!

**Comment by JamesKingdom** [comment]
This is all lossless - using [imgbot](https://imgbot.net/docs#compression) with [magick](http://www.imagemagick.org/script/index.php) compression, all dimensions are the same, but I haven't tested this.

**Pull request closed without merging**
